### PR TITLE
Improve types

### PR DESCRIPTION
**Pull request by Viicos**
A few improvements, based on https://typing.readthedocs.io/en/latest/source/stubs.html:
- No need for `from __future__ import annotations` ([source](https://typing.readthedocs.io/en/latest/source/stubs.html#syntax))
- Use `Self` where possible
- Use `TypeVar` to match possible subclasses usage of `AudioSegment`
- I think we can also use the new union syntax as well ([source](https://typing.readthedocs.io/en/latest/source/stubs.html#syntax))

### CODE REVIEW

**Comment by clo4** [comment]
Oh that's awesome. Thank you so much for contributing this! I'm about to head to sleep but I'll review/merge/release tomorrow. Really appreciate the work you put in to modernize this.

**Review by clo4 — APPROVED** [review]
All looks good to me! Thank you again for putting in the work on this. Only thing missing is adding typing_extensions to the pyproject.toml file, but that's stupid easy for me to just do myself, so don't even worry about that.

**Comment by Viicos** [comment]
Thanks for merging quickly! I'm looking at the [manim](https://github.com/ManimCommunity/manim/) dependencies to see if we they are type hinted or stubs available. Yes forgot about adding `typing_extensions`, I can open another PR and can use new union syntax in it as well

**Comment by clo4** [comment]
Sounds good - not a problem if you can’t find the time for that, but if you could, I can literally build and publish when I’m back home straight away 🙂

**Pull request merged**
